# -*- coding: utf-8 -*-
"""hello world(ideia de projeto).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKKZ2W-TXC_afeqDfN_PKPE4yyKNo2kZ
"""

import random
import time

def sensor_virtual_velocidade():
    return random.randint(0, 120)

while True:
    velocidade = sensor_virtual_velocidade()

    print(f"Velocidade simulada: {velocidade} km/h")

    print("Enviando dados para o servidor IoT...")

    time.sleep(2)